version: '3.8'

services:
  redis_service:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - main
    volumes:
      - redis_data:/data
    restart: always
  tool:
    build: .
    stdin_open: true
    environment:
      - REDIS_SERVER=redis_service
    tty: true
    volumes:
      - .:/code
    depends_on:
      - redis_service
    networks:
      - main
    restart: always

networks:
  main:

volumes:
    redis_data: